name: Green Github

on:
  schedule:
    - cron: '15 05 * * *'  # Runs at 11:15 PM Nepal time (UTC+5:45)
    - cron: '15 07 * * *'  # Runs at 1:15 PM Nepal time (UTC+5:45)
    - cron: '15 09 * * *'  # Runs at 3:15 AM Nepal time (UTC+5:45)
    - cron: '15 11 * * *'  # Runs at 5:15 PM Nepal time (UTC+5:45)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run script
        env:
          api_key: ${{ secrets.API_KEY }}
        run: |
          python greener.py
